type: object
properties:
  position:
    type: array
    description: Lat Lng
    items:
      type: number
      format: double
  station:
    type: string
    description: Station ID number
  station_name:
    type: string
    description: Name of the station
  alt:
    type: number
    description: Altitude of the station in meters
    format: double
  times:
    type: array
    description: >
      A list of strings where each string represents a UTC launch schedule
      created in the following format:

      0:00:00 (day:hour:minute) When day is set to 0 it means that the following
      launch time occurs every day When day is set to 1-7 it means the following
      launch occurs weekly on that day (Monday - Sunday)

      Hour is expressed in 24 hour time and we stick with 3 hour windows to keep
      things simple so 03, 06, 09, 12, 15, 18, 21, 24

      Minutes can be any value between 0 and 60 but we always leave this value
      at 00 (in the tracker we subtract 45 minutes from the time to generate
      predictions).
    items:
      type: string
  rs_types:
    type: array
    description: >
      The radiosonde types for this site: Supported : "07":"iMet-1",
      "11":"LMS6-403", "13":"RS92", "14":"RS92", "17":"DFM-09", "18":"DFM-06",
      "19":"MRZ-N1", "22":"RS-11G", "23":"RS41", "24":"RS41", "34":"iMet-4",
      "35":"iMS-100", "41":"RS41", "42":"RS41", "52":"RS92-NGP", "54":"DFM-17",
      "62":"MRZ-3MK", "63":"M20", "77":"M10", "82":"LMS6-1680", "84":"iMet-54"
      Unsupported : "15":"PAZA-12M", "16":"PAZA-22", "20":"MK3", "21":"1524LA
      LORAN-C/GL5000", "26":"SRS-C34", "27":"AVK-MRZ", "28":"AVK–AK2-02",
      "29":"MARZ2-2", "30":"RS2-80", "33":"GTS1-2/GFE(L)", "45":"CF-06",
      "58":"AVK-BAR", "59":"M2K2-R", "68":"AVK-RZM-2",
      "69":"MARL-A/Vektor-M-RZM-2", "73":"MARL-A", "78":"RS90", "80":"RS92",
      "88":"MARL-A/Vektor-M-MRZ", "89":"MARL-A/Vektor-M-BAR", "97":"iMet-2",
      "99":"iMet-2"

      They can either be provided as a single list of strings containing one or
      more codes: "rs_types": ["41", "07"]

      If the sondes always transmit on the same known frequency this can also be
      provided by having each code within a nested list containing the code and
      frequency: "rs_types": [["41", "404.300"], ["07", "404.200"]]
    items:
      type: string
  burst_altitude:
    type: number
    description: Average burst altitude for this site. Used for predictions
    format: double
  ascent_rate:
    type: number
    description: Typical ascent rate in m/s
    format: double
  descent_rate:
    type: number
    description: Typical descent rate in m/s
    format: double
  burst_std:
    type: number
    description: Standard deviation from analytics of burst
    format: double
  descent_std:
    type: number
    description: Standard deviation from analytics of descent rate
    format: double
  burst_samples:
    type: number
    description: Number of samples used to calculate the burst altitude
    format: double
  descent_samples:
    type: number
    description: Number of samples used to calculate the descent rate
    format: double
description: Site
